/**
 * صلاحيات الفريق حسب المنصب — مصدر واحد للحقيقة لجميع الصفحات.
 * مُحدّثة لِتطابق جدول صلاحيات-المناصب.xml (Excel).
 * الأدوار: governor, coordinator, committee_head, committee_coordinator, committee_supervisor, committee_member, budget_manager, accountant, financial_officer, member, volunteer
 */

/** أسماء المناصب بالعربية */
export const ROLE_LABELS = {
  governor: 'المشرف العام (المحافظ)',
  coordinator: 'منسق المدينة الصحية',
  committee_head: 'رئيس لجنة',
  committee_coordinator: 'منسق لجنة',
  committee_supervisor: 'مشرف لجنة',
  committee_member: 'عضو لجنة',
  member: 'عضو',
  volunteer: 'متطوع',
  budget_manager: 'مدير الميزانية',
  accountant: 'المحاسب',
  financial_officer: 'الموظف المالي',
  admin: 'مدير النظام',
};

/**
 * مصفوفة الصلاحيات لكل دور — مطابقة لجدول "مراجعة الصلاحيات حسب المنصب".
 * الأعمدة العشرة: إعدادات المدينة، إدارة الفريق، إدارة المعايير، إدارة الميزانية، اعتماد معاملات،
 * إنشاء معاملات، عرض المالية، إدارة اللجان، إدارة المبادرات، التحقق من الاستبيانات.
 */
export const PERMISSIONS_BY_ROLE = {
  governor: {
    label: ROLE_LABELS.governor,
    canManageSettings: true,
    canManageTeam: true,
    canAddTeamMember: true,
    canEditTeamMember: true,
    canDeleteTeamMember: true,
    canAddOrEditGovernor: true,
    canAddOrEditCoordinator: true,
    canManageCommittees: true,
    canManageStandards: true,
    canApproveEvidence: true,
    canManageBudget: true,
    canApproveTransactions: true,
    canCreateTransactions: true,
    canViewFinancials: true,
    canManageInitiatives: true,
    canVerifySurvey: true,
    canCreateSurvey: true,
    canViewReports: true,
    canManageTasks: true,
    canViewFiles: true,
    canUploadFiles: true,
    canManagePermissions: true,
    canManageVolunteering: true,
    canSeeDashboard: true,
    canSeeSettings: true,
    canSeeReports: true,
    canSeeStandards: true,
    canSeeInitiatives: true,
    canSeeTasks: true,
    canSeeBudget: true,
    canSeeCommittees: true,
    canSeeSurvey: true,
    canSeeVolunteering: true,
    canSeeTeam: true,
    canSeeFiles: true,
    canSeePermissions: true,
  },
  coordinator: {
    label: ROLE_LABELS.coordinator,
    canManageSettings: true,
    canManageTeam: true,
    canAddTeamMember: true,
    canEditTeamMember: true,
    canDeleteTeamMember: true,
    canAddOrEditGovernor: false,
    canAddOrEditCoordinator: false,
    canManageCommittees: true,
    canManageStandards: true,
    canApproveEvidence: true,
    canManageBudget: false,
    canApproveTransactions: false,
    canCreateTransactions: false,
    canViewFinancials: true,
    canManageInitiatives: true,
    canVerifySurvey: true,
    canCreateSurvey: true,
    canViewReports: true,
    canManageTasks: true,
    canViewFiles: true,
    canUploadFiles: true,
    canManagePermissions: true,
    canManageVolunteering: true,
    canSeeDashboard: true,
    canSeeSettings: true,
    canSeeReports: true,
    canSeeStandards: true,
    canSeeInitiatives: true,
    canSeeTasks: true,
    canSeeBudget: true,
    canSeeCommittees: true,
    canSeeVolunteering: true,
    canSeeTeam: true,
    canSeeFiles: true,
    canSeePermissions: true,
  },
  committee_head: {
    label: ROLE_LABELS.committee_head,
    canManageSettings: false,
    canManageTeam: false,
    canAddTeamMember: false,
    canEditTeamMember: false,
    canDeleteTeamMember: false,
    canAddOrEditGovernor: false,
    canAddOrEditCoordinator: false,
    canManageCommittees: false,
    canManageStandards: false,
    canApproveEvidence: true,
    canManageBudget: false,
    canApproveTransactions: false,
    canCreateTransactions: false,
    canViewFinancials: false,
    canManageInitiatives: false,
    canVerifySurvey: true,
    canCreateSurvey: true,
    canViewReports: false,
    canManageTasks: true,
    canViewFiles: true,
    canUploadFiles: true,
    canManagePermissions: false,
    canManageVolunteering: true,
    canSeeDashboard: false,
    canSeeSettings: false,
    canSeeReports: false,
    canSeeStandards: true,
    canSeeInitiatives: true,
    canSeeTasks: true,
    canSeeBudget: false,
    canSeeCommittees: true,
    canSeeSurvey: true,
    canSeeVolunteering: true,
    canSeeTeam: true,
    canSeeFiles: true,
    canSeePermissions: false,
  },
  committee_coordinator: {
    label: ROLE_LABELS.committee_coordinator,
    canManageSettings: false,
    canManageTeam: false,
    canAddTeamMember: false,
    canEditTeamMember: false,
    canDeleteTeamMember: false,
    canAddOrEditGovernor: false,
    canAddOrEditCoordinator: false,
    canManageCommittees: false,
    canManageStandards: false,
    canApproveEvidence: false,
    canManageBudget: false,
    canApproveTransactions: false,
    canCreateTransactions: false,
    canViewFinancials: false,
    canManageInitiatives: false,
    canVerifySurvey: false,
    canCreateSurvey: true,
    canViewReports: false,
    canManageTasks: true,
    canViewFiles: true,
    canUploadFiles: true,
    canManagePermissions: false,
    canManageVolunteering: false,
    canSeeDashboard: false,
    canSeeSettings: false,
    canSeeReports: false,
    canSeeStandards: true,
    canSeeInitiatives: true,
    canSeeTasks: true,
    canSeeBudget: false,
    canSeeCommittees: true,
    canSeeSurvey: true,
    canSeeVolunteering: true,
    canSeeTeam: true,
    canSeeFiles: true,
    canSeePermissions: false,
  },
  committee_supervisor: {
    label: ROLE_LABELS.committee_supervisor,
    canManageSettings: false,
    canManageTeam: false,
    canAddTeamMember: false,
    canEditTeamMember: false,
    canDeleteTeamMember: false,
    canAddOrEditGovernor: false,
    canAddOrEditCoordinator: false,
    canManageCommittees: false,
    canManageStandards: false,
    canApproveEvidence: true,
    canManageBudget: false,
    canApproveTransactions: false,
    canCreateTransactions: false,
    canViewFinancials: false,
    canManageInitiatives: false,
    canVerifySurvey: false,
    canCreateSurvey: true,
    canViewReports: false,
    canManageTasks: true,
    canViewFiles: true,
    canUploadFiles: true,
    canManagePermissions: false,
    canManageVolunteering: false,
    canSeeDashboard: false,
    canSeeSettings: false,
    canSeeReports: false,
    canSeeStandards: true,
    canSeeInitiatives: true,
    canSeeTasks: true,
    canSeeBudget: false,
    canSeeCommittees: true,
    canSeeSurvey: true,
    canSeeVolunteering: true,
    canSeeTeam: true,
    canSeeFiles: true,
    canSeePermissions: false,
  },
  budget_manager: {
    label: ROLE_LABELS.budget_manager,
    canManageSettings: false,
    canManageTeam: false,
    canAddTeamMember: false,
    canEditTeamMember: false,
    canDeleteTeamMember: false,
    canAddOrEditGovernor: false,
    canAddOrEditCoordinator: false,
    canManageCommittees: false,
    canManageStandards: false,
    canApproveEvidence: false,
    canManageBudget: true,
    canApproveTransactions: true,
    canCreateTransactions: true,
    canViewFinancials: true,
    canManageInitiatives: false,
    canVerifySurvey: false,
    canCreateSurvey: false,
    canViewReports: false,
    canManageTasks: false,
    canViewFiles: false,
    canUploadFiles: false,
    canManagePermissions: false,
    canManageVolunteering: false,
    canSeeDashboard: false,
    canSeeSettings: false,
    canSeeReports: false,
    canSeeStandards: false,
    canSeeInitiatives: false,
    canSeeTasks: false,
    canSeeBudget: true,
    canSeeCommittees: false,
    canSeeSurvey: false,
    canSeeVolunteering: false,
    canSeeTeam: false,
    canSeeFiles: false,
    canSeePermissions: false,
  },
  accountant: {
    label: ROLE_LABELS.accountant,
    canManageSettings: false,
    canManageTeam: false,
    canAddTeamMember: false,
    canEditTeamMember: false,
    canDeleteTeamMember: false,
    canAddOrEditGovernor: false,
    canAddOrEditCoordinator: false,
    canManageCommittees: false,
    canManageStandards: false,
    canApproveEvidence: false,
    canManageBudget: false,
    canApproveTransactions: false,
    canCreateTransactions: true,
    canViewFinancials: true,
    canManageInitiatives: false,
    canVerifySurvey: false,
    canCreateSurvey: false,
    canViewReports: false,
    canManageTasks: false,
    canViewFiles: false,
    canUploadFiles: false,
    canManagePermissions: false,
    canManageVolunteering: false,
    canSeeDashboard: false,
    canSeeSettings: false,
    canSeeReports: false,
    canSeeStandards: false,
    canSeeInitiatives: false,
    canSeeTasks: false,
    canSeeBudget: true,
    canSeeCommittees: false,
    canSeeSurvey: false,
    canSeeVolunteering: false,
    canSeeTeam: false,
    canSeeFiles: false,
    canSeePermissions: false,
  },
  financial_officer: {
    label: ROLE_LABELS.financial_officer,
    canManageSettings: false,
    canManageTeam: false,
    canAddTeamMember: false,
    canEditTeamMember: false,
    canDeleteTeamMember: false,
    canAddOrEditGovernor: false,
    canAddOrEditCoordinator: false,
    canManageCommittees: false,
    canManageStandards: false,
    canApproveEvidence: false,
    canManageBudget: false,
    canApproveTransactions: false,
    canCreateTransactions: false,
    canViewFinancials: true,
    canManageInitiatives: false,
    canVerifySurvey: false,
    canCreateSurvey: false,
    canViewReports: false,
    canManageTasks: false,
    canViewFiles: false,
    canUploadFiles: false,
    canManagePermissions: false,
    canManageVolunteering: false,
    canSeeDashboard: false,
    canSeeSettings: false,
    canSeeReports: false,
    canSeeStandards: false,
    canSeeInitiatives: false,
    canSeeTasks: false,
    canSeeBudget: true,
    canSeeCommittees: false,
    canSeeSurvey: false,
    canSeeVolunteering: false,
    canSeeTeam: false,
    canSeeFiles: false,
    canSeePermissions: false,
  },
  member: {
    label: ROLE_LABELS.member,
    canManageSettings: false,
    canManageTeam: false,
    canAddTeamMember: false,
    canEditTeamMember: false,
    canDeleteTeamMember: false,
    canAddOrEditGovernor: false,
    canAddOrEditCoordinator: false,
    canManageCommittees: false,
    canManageStandards: false,
    canApproveEvidence: false,
    canManageBudget: false,
    canApproveTransactions: false,
    canCreateTransactions: false,
    canViewFinancials: false,
    canManageInitiatives: false,
    canVerifySurvey: false,
    canCreateSurvey: true,
    canViewReports: false,
    canManageTasks: false,
    canViewFiles: true,
    canUploadFiles: false,
    canManagePermissions: false,
    canManageVolunteering: false,
    canSeeDashboard: false,
    canSeeSettings: false,
    canSeeReports: false,
    canSeeStandards: true,
    canSeeInitiatives: true,
    canSeeTasks: true,
    canSeeBudget: false,
    canSeeCommittees: true,
    canSeeSurvey: true,
    canSeeVolunteering: true,
    canSeeTeam: true,
    canSeeFiles: true,
    canSeePermissions: false,
  },
  volunteer: {
    label: ROLE_LABELS.volunteer,
    canManageSettings: false,
    canManageTeam: false,
    canAddTeamMember: false,
    canEditTeamMember: false,
    canDeleteTeamMember: false,
    canAddOrEditGovernor: false,
    canAddOrEditCoordinator: false,
    canManageCommittees: false,
    canManageStandards: false,
    canApproveEvidence: false,
    canManageBudget: false,
    canApproveTransactions: false,
    canCreateTransactions: false,
    canViewFinancials: false,
    canManageInitiatives: false,
    canVerifySurvey: false,
    canCreateSurvey: true,
    canViewReports: false,
    canManageTasks: false,
    canViewFiles: false,
    canUploadFiles: false,
    canManagePermissions: false,
    canManageVolunteering: false,
    canSeeDashboard: false,
    canSeeSettings: false,
    canSeeReports: false,
    canSeeStandards: false,
    canSeeInitiatives: false,
    canSeeTasks: false,
    canSeeBudget: false,
    canSeeCommittees: false,
    canSeeSurvey: true,
    canSeeVolunteering: true,
    canSeeTeam: false,
    canSeeFiles: false,
    canSeePermissions: false,
    canSeeSeedData: false,
  },
  committee_member: {
    label: ROLE_LABELS.committee_member,
    canManageSettings: false,
    canManageTeam: false,
    canAddTeamMember: false,
    canEditTeamMember: false,
    canDeleteTeamMember: false,
    canAddOrEditGovernor: false,
    canAddOrEditCoordinator: false,
    canManageCommittees: false,
    canManageStandards: false,
    canApproveEvidence: false,
    canManageBudget: false,
    canApproveTransactions: false,
    canCreateTransactions: false,
    canViewFinancials: false,
    canManageInitiatives: false,
    canVerifySurvey: false,
    canCreateSurvey: true,
    canViewReports: false,
    canManageTasks: false,
    canViewFiles: true,
    canUploadFiles: true,
    canManagePermissions: false,
    canManageVolunteering: false,
    canSeeDashboard: false,
    canSeeSettings: false,
    canSeeReports: false,
    canSeeStandards: true,
    canSeeInitiatives: true,
    canSeeTasks: true,
    canSeeBudget: false,
    canSeeCommittees: true,
    canSeeSurvey: true,
    canSeeVolunteering: true,
    canSeeTeam: true,
    canSeeFiles: true,
    canSeePermissions: false,
  },
};

// admin يُعامل كـ governor
PERMISSIONS_BY_ROLE.admin = PERMISSIONS_BY_ROLE.governor;

/**
 * أعمدة جدول "مراجعة الصلاحيات حسب المنصب" — مصدر واحد للحقيقة مع PERMISSIONS_BY_ROLE.
 */
export const PERMISSION_REVIEW_KEYS = [
  { key: 'canManageSettings', label: 'إعدادات المدينة' },
  { key: 'canManageTeam', label: 'إدارة الفريق' },
  { key: 'canAddTeamMember', label: 'إضافة عضو' },
  { key: 'canEditTeamMember', label: 'تعديل عضو' },
  { key: 'canDeleteTeamMember', label: 'حذف عضو' },
  { key: 'canAddOrEditGovernor', label: 'إضافة/تعديل محافظ' },
  { key: 'canAddOrEditCoordinator', label: 'إضافة/تعديل منسق' },
  { key: 'canManageCommittees', label: 'إدارة اللجان' },
  { key: 'canManageStandards', label: 'إدارة المعايير' },
  { key: 'canApproveEvidence', label: 'اعتماد أدلة' },
  { key: 'canManageBudget', label: 'إدارة الميزانية' },
  { key: 'canApproveTransactions', label: 'اعتماد معاملات' },
  { key: 'canCreateTransactions', label: 'إنشاء معاملات' },
  { key: 'canViewFinancials', label: 'عرض المالية' },
  { key: 'canManageInitiatives', label: 'إدارة المبادرات' },
  { key: 'canVerifySurvey', label: 'التحقق من الاستبيانات' },
  { key: 'canCreateSurvey', label: 'إنشاء استبيان' },
  { key: 'canViewReports', label: 'عرض التقارير' },
  { key: 'canManageTasks', label: 'إدارة المهام' },
  { key: 'canViewFiles', label: 'عرض الملفات' },
  { key: 'canUploadFiles', label: 'رفع ملفات' },
  { key: 'canManagePermissions', label: 'إدارة الصلاحيات' },
  { key: 'canSeeDashboard', label: 'رابط لوحة التحكم' },
  { key: 'canSeeSettings', label: 'دخول لوحة الإعدادات' },
  { key: 'canSeeReports', label: 'رابط التقارير' },
  { key: 'canSeeStandards', label: 'رابط المعايير' },
  { key: 'canSeeInitiatives', label: 'رابط المبادرات' },
  { key: 'canSeeTasks', label: 'رابط المهام' },
  { key: 'canSeeBudget', label: 'رابط الميزانية' },
  { key: 'canSeeCommittees', label: 'رابط اللجان' },
  { key: 'canSeeSurvey', label: 'رابط المسح الميداني' },
  { key: 'canManageVolunteering', label: 'إدارة التطوع' },
  { key: 'canSeeVolunteering', label: 'رابط التطوع' },
  { key: 'canSeeTeam', label: 'رابط الفريق' },
  { key: 'canSeeFiles', label: 'رابط الملفات' },
  { key: 'canSeePermissions', label: 'رابط لوحة الصلاحيات' },
];

/** ترتيب المناصب في جدول مراجعة الصلاحيات */
export const PERMISSIONS_REVIEW_ROLE_ORDER = [
  'governor', 'coordinator', 'committee_head', 'committee_coordinator', 'committee_supervisor',
  'committee_member', 'budget_manager', 'accountant', 'financial_officer', 'member', 'volunteer'
];

/**
 * إرجاع صلاحيات الدور. إذا لم يُعرَف الدور يُعامل كـ volunteer.
 * @param {string} role - governor | coordinator | committee_head | committee_coordinator | committee_supervisor | member | volunteer | budget_manager | accountant | financial_officer | admin
 * @returns {Object} كائن الصلاحيات
 */
export function getPermissions(role) {
  const r = role === 'admin' ? 'governor' : (role || 'volunteer');
  return PERMISSIONS_BY_ROLE[r] ?? PERMISSIONS_BY_ROLE.volunteer;
}

/** عناصر القائمة الافتراضية مع مفتاح الصلاحية لكل عنصر */
export const NAV_ITEMS = [
  { name: 'Dashboard', label: 'لوحة التحكم', icon: 'LayoutDashboard', permission: 'canSeeDashboard' },
  { name: 'Reports', label: 'التقارير', icon: 'FileSearch', permission: 'canSeeReports' },
  { name: 'Standards', label: 'المعايير', icon: 'Target', permission: 'canSeeStandards' },
  { name: 'Initiatives', label: 'المبادرات', icon: 'Lightbulb', permission: 'canSeeInitiatives' },
  { name: 'Tasks', label: 'المهام', icon: 'ClipboardList', permission: 'canSeeTasks' },
  { name: 'Budget', label: 'الميزانية', icon: 'DollarSign', permission: 'canSeeBudget' },
  { name: 'Committees', label: 'اللجان', icon: 'Building', permission: 'canSeeCommittees' },
  { name: 'Survey', label: 'المسح الميداني', icon: 'ClipboardList', permission: 'canSeeSurvey' },
  { name: 'Volunteering', label: 'التطوع', icon: 'HandHelping', permission: 'canSeeVolunteering' },
  { name: 'TeamManagement', label: 'الفريق', icon: 'Users', permission: 'canSeeTeam' },
  { name: 'Files', label: 'الملفات', icon: 'FolderOpen', permission: 'canSeeFiles' },
  { name: 'PermissionsManager', label: 'الصلاحيات', icon: 'Shield', permission: 'canSeePermissions' },
];

/**
 * إرجاع عناصر القائمة المرئية للدور المحدد.
 * @param {string} role
 * @returns {Array<{name, label, icon}>}
 */
export function getNavItemsForRole(role) {
  const perms = getPermissions(role);
  return NAV_ITEMS.filter((item) => perms[item.permission] !== false);
}
