/**
 * صلاحيات الفريق حسب المنصب — مصدر واحد للحقيقة لجميع الصفحات.
 * الأدوار: governor, coordinator, committee_head, member, volunteer, budget_manager, accountant, financial_officer
 */

/** أسماء المناصب بالعربية */
export const ROLE_LABELS = {
  governor: 'المشرف العام (المحافظ)',
  coordinator: 'منسق المدينة الصحية',
  committee_head: 'رئيس لجنة',
  committee_coordinator: 'منسق لجنة',
  committee_supervisor: 'مشرف لجنة',
  committee_member: 'عضو لجنة',
  member: 'عضو',
  volunteer: 'متطوع',
  budget_manager: 'مدير الميزانية',
  accountant: 'المحاسب',
  financial_officer: 'الموظف المالي',
  admin: 'مدير النظام',
};

/**
 * مصفوفة الصلاحيات لكل دور.
 * يمكن استخدامها في واجهة "مراجعة الصلاحيات" أو التوثيق.
 */
export const PERMISSIONS_BY_ROLE = {
  governor: {
    label: ROLE_LABELS.governor,
    // إدارة النظام والمدينة
    canManageSettings: true,
    canManageTeam: true,
    canAddTeamMember: true,
    canEditTeamMember: true,
    canDeleteTeamMember: true,
    canAddOrEditGovernor: true,
    canManageCommittees: true,
    // المعايير والأدلة
    canManageStandards: true,
    canApproveEvidence: true,
    // الميزانية والمالية
    canManageBudget: true,
    canApproveTransactions: true,
    canCreateTransactions: true,
    canViewFinancials: true,
    // المحتوى والتقارير
    canManageInitiatives: true,
    canVerifySurvey: true,
    canViewReports: true,
    canManageTasks: true,
    canViewFiles: true,
    canUploadFiles: true,
    // القائمة
    canSeeDashboard: true,
    canSeeReports: true,
    canSeeStandards: true,
    canSeeInitiatives: true,
    canSeeTasks: true,
    canSeeBudget: true,
    canSeeCommittees: true,
    canSeeTeam: true,
    canSeeFiles: true,
  },
  coordinator: {
    label: ROLE_LABELS.coordinator,
    canManageSettings: false,
    canManageTeam: true,
    canAddTeamMember: true,
    canEditTeamMember: false,
    canDeleteTeamMember: false,
    canAddOrEditGovernor: false,
    canManageCommittees: true,
    canManageStandards: true,
    canApproveEvidence: true,
    canManageBudget: false,
    canApproveTransactions: false,
    canCreateTransactions: true,
    canViewFinancials: true,
    canManageInitiatives: true,
    canVerifySurvey: true,
    canViewReports: true,
    canManageTasks: true,
    canViewFiles: true,
    canUploadFiles: true,
    canSeeDashboard: true,
    canSeeReports: true,
    canSeeStandards: true,
    canSeeInitiatives: true,
    canSeeTasks: true,
    canSeeBudget: true,
    canSeeCommittees: true,
    canSeeTeam: true,
    canSeeFiles: true,
  },
  committee_head: {
    label: ROLE_LABELS.committee_head,
    canManageSettings: false,
    canManageTeam: false,
    canAddTeamMember: false,
    canEditTeamMember: false,
    canDeleteTeamMember: false,
    canAddOrEditGovernor: false,
    canManageCommittees: false,
    canManageStandards: false,
    canApproveEvidence: true,
    canManageBudget: false,
    canApproveTransactions: false,
    canCreateTransactions: true,
    canViewFinancials: true,
    canManageInitiatives: true,
    canVerifySurvey: true,
    canViewReports: true,
    canManageTasks: true,
    canViewFiles: true,
    canUploadFiles: true,
    canSeeDashboard: true,
    canSeeReports: true,
    canSeeStandards: true,
    canSeeInitiatives: true,
    canSeeTasks: true,
    canSeeBudget: true,
    canSeeCommittees: true,
    canSeeTeam: true,
    canSeeFiles: true,
  },
  committee_coordinator: {
    label: ROLE_LABELS.committee_coordinator,
    canManageSettings: false,
    canManageTeam: false,
    canAddTeamMember: false,
    canEditTeamMember: false,
    canDeleteTeamMember: false,
    canAddOrEditGovernor: false,
    canManageCommittees: false,
    canManageStandards: false,
    canApproveEvidence: true,
    canManageBudget: false,
    canApproveTransactions: false,
    canCreateTransactions: true,
    canViewFinancials: true,
    canManageInitiatives: true,
    canVerifySurvey: true,
    canViewReports: true,
    canManageTasks: true,
    canViewFiles: true,
    canUploadFiles: true,
    canSeeDashboard: true,
    canSeeReports: true,
    canSeeStandards: true,
    canSeeInitiatives: true,
    canSeeTasks: true,
    canSeeBudget: true,
    canSeeCommittees: true,
    canSeeTeam: true,
    canSeeFiles: true,
  },
  committee_supervisor: {
    label: ROLE_LABELS.committee_supervisor,
    canManageSettings: false,
    canManageTeam: false,
    canAddTeamMember: false,
    canEditTeamMember: false,
    canDeleteTeamMember: false,
    canAddOrEditGovernor: false,
    canManageCommittees: false,
    canManageStandards: false,
    canApproveEvidence: true,
    canManageBudget: false,
    canApproveTransactions: false,
    canCreateTransactions: true,
    canViewFinancials: true,
    canManageInitiatives: true,
    canVerifySurvey: true,
    canViewReports: true,
    canManageTasks: true,
    canViewFiles: true,
    canUploadFiles: true,
    canSeeDashboard: true,
    canSeeReports: true,
    canSeeStandards: true,
    canSeeInitiatives: true,
    canSeeTasks: true,
    canSeeBudget: true,
    canSeeCommittees: true,
    canSeeTeam: true,
    canSeeFiles: true,
  },
  budget_manager: {
    label: ROLE_LABELS.budget_manager,
    canManageSettings: false,
    canManageTeam: false,
    canAddTeamMember: false,
    canEditTeamMember: false,
    canDeleteTeamMember: false,
    canAddOrEditGovernor: false,
    canManageCommittees: false,
    canManageStandards: false,
    canApproveEvidence: false,
    canManageBudget: true,
    canApproveTransactions: true,
    canCreateTransactions: true,
    canViewFinancials: true,
    canManageInitiatives: false,
    canVerifySurvey: false,
    canViewReports: false,
    canManageTasks: false,
    canViewFiles: false,
    canUploadFiles: false,
    canSeeDashboard: false,
    canSeeReports: false,
    canSeeStandards: false,
    canSeeInitiatives: false,
    canSeeTasks: false,
    canSeeBudget: true,
    canSeeCommittees: false,
    canSeeTeam: false,
    canSeeFiles: false,
  },
  accountant: {
    label: ROLE_LABELS.accountant,
    canManageSettings: false,
    canManageTeam: false,
    canAddTeamMember: false,
    canEditTeamMember: false,
    canDeleteTeamMember: false,
    canAddOrEditGovernor: false,
    canManageCommittees: false,
    canManageStandards: false,
    canApproveEvidence: false,
    canManageBudget: false,
    canApproveTransactions: false,
    canCreateTransactions: true,
    canViewFinancials: true,
    canManageInitiatives: false,
    canVerifySurvey: false,
    canViewReports: false,
    canManageTasks: false,
    canViewFiles: false,
    canUploadFiles: false,
    canSeeDashboard: false,
    canSeeReports: false,
    canSeeStandards: false,
    canSeeInitiatives: false,
    canSeeTasks: false,
    canSeeBudget: true,
    canSeeCommittees: false,
    canSeeTeam: false,
    canSeeFiles: false,
  },
  financial_officer: {
    label: ROLE_LABELS.financial_officer,
    canManageSettings: false,
    canManageTeam: false,
    canAddTeamMember: false,
    canEditTeamMember: false,
    canDeleteTeamMember: false,
    canAddOrEditGovernor: false,
    canManageCommittees: false,
    canManageStandards: false,
    canApproveEvidence: false,
    canManageBudget: false,
    canApproveTransactions: false,
    canCreateTransactions: true,
    canViewFinancials: true,
    canManageInitiatives: false,
    canVerifySurvey: false,
    canViewReports: false,
    canManageTasks: false,
    canViewFiles: false,
    canUploadFiles: false,
    canSeeDashboard: false,
    canSeeReports: false,
    canSeeStandards: false,
    canSeeInitiatives: false,
    canSeeTasks: false,
    canSeeBudget: true,
    canSeeCommittees: false,
    canSeeTeam: false,
    canSeeFiles: false,
  },
  member: {
    label: ROLE_LABELS.member,
    canManageSettings: false,
    canManageTeam: false,
    canAddTeamMember: false,
    canEditTeamMember: false,
    canDeleteTeamMember: false,
    canAddOrEditGovernor: false,
    canManageCommittees: false,
    canManageStandards: false,
    canApproveEvidence: false,
    canManageBudget: false,
    canApproveTransactions: false,
    canCreateTransactions: false,
    canViewFinancials: false,
    canManageInitiatives: false,
    canVerifySurvey: false,
    canViewReports: true,
    canManageTasks: false,
    canViewFiles: true,
    canUploadFiles: true,
    canSeeDashboard: true,
    canSeeReports: true,
    canSeeStandards: true,
    canSeeInitiatives: true,
    canSeeTasks: true,
    canSeeBudget: false,
    canSeeCommittees: true,
    canSeeTeam: true,
    canSeeFiles: true,
  },
  volunteer: {
    label: ROLE_LABELS.volunteer,
    canManageSettings: false,
    canManageTeam: false,
    canAddTeamMember: false,
    canEditTeamMember: false,
    canDeleteTeamMember: false,
    canAddOrEditGovernor: false,
    canManageCommittees: false,
    canManageStandards: false,
    canApproveEvidence: false,
    canManageBudget: false,
    canApproveTransactions: false,
    canCreateTransactions: false,
    canViewFinancials: false,
    canManageInitiatives: false,
    canVerifySurvey: false,
    canViewReports: true,
    canManageTasks: false,
    canViewFiles: true,
    canUploadFiles: true,
    canSeeDashboard: true,
    canSeeReports: true,
    canSeeStandards: true,
    canSeeInitiatives: true,
    canSeeTasks: true,
    canSeeBudget: false,
    canSeeCommittees: true,
    canSeeTeam: true,
    canSeeFiles: true,
  },
  committee_member: {
    label: ROLE_LABELS.committee_member,
    canManageSettings: false,
    canManageTeam: false,
    canAddTeamMember: false,
    canEditTeamMember: false,
    canDeleteTeamMember: false,
    canAddOrEditGovernor: false,
    canManageCommittees: false,
    canManageStandards: false,
    canApproveEvidence: false,
    canManageBudget: false,
    canApproveTransactions: false,
    canCreateTransactions: false,
    canViewFinancials: false,
    canManageInitiatives: false,
    canVerifySurvey: false,
    canViewReports: true,
    canManageTasks: false,
    canViewFiles: true,
    canUploadFiles: true,
    canSeeDashboard: true,
    canSeeReports: true,
    canSeeStandards: true,
    canSeeInitiatives: true,
    canSeeTasks: true,
    canSeeBudget: false,
    canSeeCommittees: true,
    canSeeTeam: true,
    canSeeFiles: true,
  },
};

// admin (Base44) يُعامل كـ governor
PERMISSIONS_BY_ROLE.admin = PERMISSIONS_BY_ROLE.governor;

/**
 * إرجاع صلاحيات الدور. إذا لم يُعرَف الدور يُعامل كـ volunteer.
 * @param {string} role - governor | coordinator | committee_head | committee_coordinator | committee_supervisor | member | volunteer | budget_manager | accountant | financial_officer | admin
 * @returns {Object} كائن الصلاحيات
 */
export function getPermissions(role) {
  const r = role === 'admin' ? 'governor' : (role || 'volunteer');
  return PERMISSIONS_BY_ROLE[r] ?? PERMISSIONS_BY_ROLE.volunteer;
}

/** عناصر القائمة الافتراضية مع مفتاح الصلاحية لكل عنصر */
export const NAV_ITEMS = [
  { name: 'Dashboard', label: 'لوحة التحكم', icon: 'LayoutDashboard', permission: 'canSeeDashboard' },
  { name: 'Reports', label: 'التقارير', icon: 'FileSearch', permission: 'canSeeReports' },
  { name: 'Standards', label: 'المعايير', icon: 'Target', permission: 'canSeeStandards' },
  { name: 'Initiatives', label: 'المبادرات', icon: 'Lightbulb', permission: 'canSeeInitiatives' },
  { name: 'Tasks', label: 'المهام', icon: 'ClipboardList', permission: 'canSeeTasks' },
  { name: 'Budget', label: 'الميزانية', icon: 'DollarSign', permission: 'canSeeBudget' },
  { name: 'Committees', label: 'اللجان', icon: 'Building', permission: 'canSeeCommittees' },
  { name: 'TeamManagement', label: 'الفريق', icon: 'Users', permission: 'canSeeTeam' },
  { name: 'Files', label: 'الملفات', icon: 'FolderOpen', permission: 'canSeeFiles' },
];

/**
 * إرجاع عناصر القائمة المرئية للدور المحدد.
 * @param {string} role
 * @returns {Array<{name, label, icon}>}
 */
export function getNavItemsForRole(role) {
  const perms = getPermissions(role);
  return NAV_ITEMS.filter((item) => perms[item.permission] !== false);
}
